#
# For all clippy lints please visit: https://rust-lang.github.io/rust-clippy/master/
#
deny = [
    'clippy::await_holding_lock',
    'clippy::cast_lossless',
    'clippy::cloned_instead_of_copied',
    'clippy::correctness',
    'clippy::create_dir',
    'clippy::dbg_macro',
    'clippy::else_if_without_else',
    'clippy::explicit_into_iter_loop',
    'clippy::explicit_iter_loop',
    'clippy::if_not_else',
    'clippy::inline_always',
    'clippy::let_underscore_drop',
    'clippy::let_unit_value',
    'clippy::match_bool',
    'clippy::match_on_vec_items',
    'clippy::match_wild_err_arm',
    'clippy::needless_borrow',
    'clippy::needless_question_mark',
    'clippy::nonminimal_bool',
    'clippy::range_plus_one',
    'clippy::style',
    'clippy::too_many_lines',
    'clippy::trivially_copy_pass_by_ref',
    'clippy::unnecessary_to_owned',
    'dead_code',
    'unknown_lints',
    'unreachable_patterns',
    'unused_extern_crates',
    'unused_imports',
    'unused_must_use',
    'unused_variables',
]
allow = [
    'clippy::bool-assert-comparison',
    'clippy::default_trait_access',
    'clippy::struct_excessive_bools',
    'clippy::too_many_arguments',
]
warn = []
