use crate::models::common::{License, Permissions, Url, Visibility};
use crate::models::user::SimpleUser;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Repository {
    pub archive_url: Url,
    pub assignees_url: Url,
    pub blobs_url: Url,
    pub branches_url: Url,
    pub collaborators_url: Url,
    pub comments_url: Url,
    pub commits_url: Url,
    pub compare_url: Url,
    pub contents_url: Url,
    pub contributors_url: Url,
    pub deployments_url: Url,
    pub description: String,
    pub downloads_url: Url,
    pub events_url: Url,
    pub fork: bool,
    pub forks_url: Url,
    pub full_name: String,
    pub git_commits_url: Url,
    pub git_refs_url: Url,
    pub git_tags_url: Url,
    pub hooks_url: Url,
    pub html_url: Url,
    pub id: u64,
    pub node_id: String,
    pub issue_comment_url: Url,
    pub issue_events_url: Url,
    pub issues_url: Url,
    pub keys_url: Url,
    pub labels_url: Url,
    pub languages_url: Url,
    pub merges_url: Url,
    pub milestones_url: Url,
    pub name: String,
    pub notifications_url: Url,
    pub owner: SimpleUser,
    pub private: bool,
    pub pulls_url: Url,
    pub releases_url: Url,
    pub stargazers_url: Url,
    pub statuses_url: Url,
    pub subscribers_url: Url,
    pub subscription_url: Url,
    pub tags_url: Url,
    pub teams_url: Url,
    pub trees_url: Url,
    pub url: Url,
    pub clone_url: Url,
    pub default_branch: String,
    pub forks: u64,
    pub forks_count: u64,
    pub git_url: Url,
    pub has_downloads: bool,
    pub has_issues: bool,
    pub has_projects: bool,
    pub has_wiki: bool,
    pub has_pages: bool,
    pub homepage: String,
    pub language: String,
    pub master_branch: Option<String>,
    pub archived: bool,
    pub disabled: bool,
    pub visibility: Visibility,
    pub mirror_url: Option<Url>,
    pub open_issues: u64,
    pub open_issues_count: u64,
    pub permissions: Option<Permissions>,
    pub temp_clone_token: Option<String>,
    pub allow_merge_commit: Option<bool>,
    pub allow_squash_merge: Option<bool>,
    pub allow_rebase_merge: Option<bool>,
    pub license: License,
    pub pushed_at: String,
    pub size: u64,
    pub ssh_url: Url,
    pub stargazers_count: u64,
    pub svn_url: Url,
    pub topics: Vec<String>,
    pub watchers: u64,
    pub watchers_count: u64,
    pub created_at: String,
    pub updated_at: String,
    pub allow_forking: bool,
    pub is_template: bool,
}

#[cfg(test)]
mod test {
    use crate::models::repository::Repository;

    const TARI_REPO: &str = r#"
{
    "id": 136459099,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMzY0NTkwOTk=",
    "name": "tari",
    "full_name": "tari-project/tari",
    "private": false,
    "owner": {
        "login": "tari-project",
        "id": 37560539,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
        "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tari-project",
        "html_url": "https://github.com/tari-project",
        "followers_url": "https://api.github.com/users/tari-project/followers",
        "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
        "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
        "organizations_url": "https://api.github.com/users/tari-project/orgs",
        "repos_url": "https://api.github.com/users/tari-project/repos",
        "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tari-project/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "html_url": "https://github.com/tari-project/tari",
    "description": "The Tari protocol",
    "fork": false,
    "url": "https://api.github.com/repos/tari-project/tari",
    "forks_url": "https://api.github.com/repos/tari-project/tari/forks",
    "keys_url": "https://api.github.com/repos/tari-project/tari/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/tari-project/tari/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/tari-project/tari/teams",
    "hooks_url": "https://api.github.com/repos/tari-project/tari/hooks",
    "issue_events_url": "https://api.github.com/repos/tari-project/tari/issues/events{/number}",
    "events_url": "https://api.github.com/repos/tari-project/tari/events",
    "assignees_url": "https://api.github.com/repos/tari-project/tari/assignees{/user}",
    "branches_url": "https://api.github.com/repos/tari-project/tari/branches{/branch}",
    "tags_url": "https://api.github.com/repos/tari-project/tari/tags",
    "blobs_url": "https://api.github.com/repos/tari-project/tari/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/tari-project/tari/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/tari-project/tari/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/tari-project/tari/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/tari-project/tari/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/tari-project/tari/languages",
    "stargazers_url": "https://api.github.com/repos/tari-project/tari/stargazers",
    "contributors_url": "https://api.github.com/repos/tari-project/tari/contributors",
    "subscribers_url": "https://api.github.com/repos/tari-project/tari/subscribers",
    "subscription_url": "https://api.github.com/repos/tari-project/tari/subscription",
    "commits_url": "https://api.github.com/repos/tari-project/tari/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/tari-project/tari/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/tari-project/tari/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/tari-project/tari/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/tari-project/tari/contents/{+path}",
    "compare_url": "https://api.github.com/repos/tari-project/tari/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/tari-project/tari/merges",
    "archive_url": "https://api.github.com/repos/tari-project/tari/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/tari-project/tari/downloads",
    "issues_url": "https://api.github.com/repos/tari-project/tari/issues{/number}",
    "pulls_url": "https://api.github.com/repos/tari-project/tari/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/tari-project/tari/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/tari-project/tari/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/tari-project/tari/labels{/name}",
    "releases_url": "https://api.github.com/repos/tari-project/tari/releases{/id}",
    "deployments_url": "https://api.github.com/repos/tari-project/tari/deployments",
    "created_at": "2018-06-07T10:09:08Z",
    "updated_at": "2022-08-03T01:21:52Z",
    "pushed_at": "2022-08-05T14:00:50Z",
    "git_url": "git://github.com/tari-project/tari.git",
    "ssh_url": "git@github.com:tari-project/tari.git",
    "clone_url": "https://github.com/tari-project/tari.git",
    "svn_url": "https://github.com/tari-project/tari",
    "homepage": "https://tari.com",
    "size": 115832,
    "stargazers_count": 275,
    "watchers_count": 275,
    "language": "Rust",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "forks_count": 530,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 109,
    "license": {
        "key": "bsd-3-clause",
        "name": "BSD 3-Clause \"New\" or \"Revised\" License",
        "spdx_id": "BSD-3-Clause",
        "url": "https://api.github.com/licenses/bsd-3-clause",
        "node_id": "MDc6TGljZW5zZTU="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "hacktoberfest",
        "rust",
        "tari"
    ],
    "visibility": "public",
    "forks": 530,
    "open_issues": 109,
    "watchers": 275,
    "default_branch": "development",
    "temp_clone_token": null,
    "organization": {
        "login": "tari-project",
        "id": 37560539,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
        "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tari-project",
        "html_url": "https://github.com/tari-project",
        "followers_url": "https://api.github.com/users/tari-project/followers",
        "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
        "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
        "organizations_url": "https://api.github.com/users/tari-project/orgs",
        "repos_url": "https://api.github.com/users/tari-project/repos",
        "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tari-project/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "network_count": 530,
    "subscribers_count": 29
}
    "#;

    #[test]
    fn tari_repo_deserializes() {
        let tari: Repository = serde_json::from_str(TARI_REPO).unwrap();
        assert_eq!(tari.id, 136459099);
        assert_eq!(tari.name, "tari");
        assert_eq!(tari.owner.node_id, "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5");
        assert_eq!(tari.license.spdx_id, "BSD-3-Clause");
    }
}
