pub mod comments {
    pub const COMMENT: &str = r#"{
        "url": "https://api.github.com/repos/tari-project/tari/pulls/comments/344116934",
        "pull_request_review_id": 314124780,
        "id": 344116934,
        "node_id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM0NDExNjkzNA==",
        "diff_hunk": "@@ -482,8 +482,9 @@ where T: BlockchainBackend\n     pub fn is_new_best_block(&self, block: &Block) -> Result<bool, ChainStorageError> {\n         let (height, parent_hash) = {\n             let db = self.access_metadata()?;\n+            // If the database is empty, the best block must be the genesis block\n             if db.height_of_longest_chain.is_none() {\n-                return Ok(true);\n+                return Ok(block.header.height == 0);",
        "path": "base_layer/core/src/chain_storage/blockchain_database.rs",
        "position": 7,
        "original_position": 7,
        "commit_id": "f862e3d6ed6c9158ad51d77c14af839b1e45489f",
        "original_commit_id": "f862e3d6ed6c9158ad51d77c14af839b1e45489f",
        "user": {
            "login": "SWvheerden",
            "id": 2579813,
            "node_id": "MDQ6VXNlcjI1Nzk4MTM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2579813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SWvheerden",
            "html_url": "https://github.com/SWvheerden",
            "followers_url": "https://api.github.com/users/SWvheerden/followers",
            "following_url": "https://api.github.com/users/SWvheerden/following{/other_user}",
            "gists_url": "https://api.github.com/users/SWvheerden/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SWvheerden/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SWvheerden/subscriptions",
            "organizations_url": "https://api.github.com/users/SWvheerden/orgs",
            "repos_url": "https://api.github.com/users/SWvheerden/repos",
            "events_url": "https://api.github.com/users/SWvheerden/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SWvheerden/received_events",
            "type": "User",
            "site_admin": false
        },
        "body": "Current RFC says Gen is height 1, not 0",
        "created_at": "2019-11-08T10:46:22Z",
        "updated_at": "2019-11-08T10:46:30Z",
        "html_url": "https://github.com/tari-project/tari/pull/1000#discussion_r344116934",
        "pull_request_url": "https://api.github.com/repos/tari-project/tari/pulls/1000",
        "author_association": "COLLABORATOR",
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/tari-project/tari/pulls/comments/344116934"
            },
            "html": {
                "href": "https://github.com/tari-project/tari/pull/1000#discussion_r344116934"
            },
            "pull_request": {
                "href": "https://api.github.com/repos/tari-project/tari/pulls/1000"
            }
        },
        "reactions": {
            "url": "https://api.github.com/repos/tari-project/tari/pulls/comments/344116934/reactions",
            "total_count": 0,
            "+1": 12,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "start_line": null,
        "original_start_line": null,
        "start_side": null,
        "line": 487,
        "original_line": 487,
        "side": "RIGHT"
    }"#;
}

pub mod labels {
    pub const LABELS: &str = r#"
[
    {
        "id": 1189345686,
        "node_id": "MDU6TGFiZWwxMTg5MzQ1Njg2",
        "url": "https://api.github.com/repos/tari-project/tari/labels/in%20progress",
        "name": "in progress",
        "color": "ededed",
        "default": false,
        "description": null
    },
    {
        "id": 1390045826,
        "node_id": "MDU6TGFiZWwxMzkwMDQ1ODI2",
        "url": "https://api.github.com/repos/tari-project/tari/labels/Integration%20test",
        "name": "Integration test",
        "color": "f435f9",
        "default": false,
        "description": ""
    },
    {
        "id": 957513340,
        "node_id": "MDU6TGFiZWw5NTc1MTMzNDA=",
        "url": "https://api.github.com/repos/tari-project/tari/labels/invalid",
        "name": "invalid",
        "color": "e4e669",
        "default": true,
        "description": "This doesn't seem right"
    },
    {
        "id": 4274976216,
        "node_id": "LA_kwDOCCIzW87-zvXY",
        "url": "https://api.github.com/repos/tari-project/tari/labels/javascript",
        "name": "javascript",
        "color": "168700",
        "default": false,
        "description": "Pull requests that update Javascript code"
    },
    {
        "id": 2024296734,
        "node_id": "MDU6TGFiZWwyMDI0Mjk2NzM0",
        "url": "https://api.github.com/repos/tari-project/tari/labels/Known-Issue",
        "name": "Known-Issue",
        "color": "bfdadc",
        "default": false,
        "description": "Issue that has already been discovered"
    }
]
    "#;
}

pub mod pull_requests {
    pub const TARI_PR_1K: &str = r#"
{
    "url": "https://api.github.com/repos/tari-project/tari/pulls/1000",
    "id": 338616778,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MzM4NjE2Nzc4",
    "html_url": "https://github.com/tari-project/tari/pull/1000",
    "diff_url": "https://github.com/tari-project/tari/pull/1000.diff",
    "patch_url": "https://github.com/tari-project/tari/pull/1000.patch",
    "issue_url": "https://api.github.com/repos/tari-project/tari/issues/1000",
    "number": 1000,
    "state": "closed",
    "locked": false,
    "title": "Check that 1st block into DB is the Genesis block",
    "user": {
        "login": "CjS77",
        "id": 7573551,
        "node_id": "MDQ6VXNlcjc1NzM1NTE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7573551?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CjS77",
        "html_url": "https://github.com/CjS77",
        "followers_url": "https://api.github.com/users/CjS77/followers",
        "following_url": "https://api.github.com/users/CjS77/following{/other_user}",
        "gists_url": "https://api.github.com/users/CjS77/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CjS77/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CjS77/subscriptions",
        "organizations_url": "https://api.github.com/users/CjS77/orgs",
        "repos_url": "https://api.github.com/users/CjS77/repos",
        "events_url": "https://api.github.com/users/CjS77/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CjS77/received_events",
        "type": "User",
        "site_admin": false
    },
    "body": "When adding a new block, if the DB is empty,\r\n`is_best_block` should only return true if\r\nthe block is the Gensis block\r\n\r\n",
    "created_at": "2019-11-08T10:42:52Z",
    "updated_at": "2019-11-11T11:15:46Z",
    "closed_at": "2019-11-11T11:15:20Z",
    "merged_at": "2019-11-11T11:15:20Z",
    "merge_commit_sha": "f862e3d6ed6c9158ad51d77c14af839b1e45489f",
    "assignee": null,
    "assignees": [],
    "requested_reviewers": [],
    "requested_teams": [],
    "labels": [],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/tari-project/tari/pulls/1000/commits",
    "review_comments_url": "https://api.github.com/repos/tari-project/tari/pulls/1000/comments",
    "review_comment_url": "https://api.github.com/repos/tari-project/tari/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/tari-project/tari/issues/1000/comments",
    "statuses_url": "https://api.github.com/repos/tari-project/tari/statuses/f862e3d6ed6c9158ad51d77c14af839b1e45489f",
    "head": {
        "label": "tari-project:genesis_block_check",
        "ref": "genesis_block_check",
        "sha": "f862e3d6ed6c9158ad51d77c14af839b1e45489f",
        "user": {
            "login": "tari-project",
            "id": 37560539,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
            "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tari-project",
            "html_url": "https://github.com/tari-project",
            "followers_url": "https://api.github.com/users/tari-project/followers",
            "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
            "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
            "organizations_url": "https://api.github.com/users/tari-project/orgs",
            "repos_url": "https://api.github.com/users/tari-project/repos",
            "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tari-project/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "repo": {
            "id": 136459099,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMzY0NTkwOTk=",
            "name": "tari",
            "full_name": "tari-project/tari",
            "private": false,
            "owner": {
                "login": "tari-project",
                "id": 37560539,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
                "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/tari-project",
                "html_url": "https://github.com/tari-project",
                "followers_url": "https://api.github.com/users/tari-project/followers",
                "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
                "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
                "organizations_url": "https://api.github.com/users/tari-project/orgs",
                "repos_url": "https://api.github.com/users/tari-project/repos",
                "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
                "received_events_url": "https://api.github.com/users/tari-project/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/tari-project/tari",
            "description": "The Tari protocol",
            "fork": false,
            "url": "https://api.github.com/repos/tari-project/tari",
            "forks_url": "https://api.github.com/repos/tari-project/tari/forks",
            "keys_url": "https://api.github.com/repos/tari-project/tari/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/tari-project/tari/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/tari-project/tari/teams",
            "hooks_url": "https://api.github.com/repos/tari-project/tari/hooks",
            "issue_events_url": "https://api.github.com/repos/tari-project/tari/issues/events{/number}",
            "events_url": "https://api.github.com/repos/tari-project/tari/events",
            "assignees_url": "https://api.github.com/repos/tari-project/tari/assignees{/user}",
            "branches_url": "https://api.github.com/repos/tari-project/tari/branches{/branch}",
            "tags_url": "https://api.github.com/repos/tari-project/tari/tags",
            "blobs_url": "https://api.github.com/repos/tari-project/tari/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/tari-project/tari/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/tari-project/tari/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/tari-project/tari/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/tari-project/tari/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/tari-project/tari/languages",
            "stargazers_url": "https://api.github.com/repos/tari-project/tari/stargazers",
            "contributors_url": "https://api.github.com/repos/tari-project/tari/contributors",
            "subscribers_url": "https://api.github.com/repos/tari-project/tari/subscribers",
            "subscription_url": "https://api.github.com/repos/tari-project/tari/subscription",
            "commits_url": "https://api.github.com/repos/tari-project/tari/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/tari-project/tari/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/tari-project/tari/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/tari-project/tari/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/tari-project/tari/contents/{+path}",
            "compare_url": "https://api.github.com/repos/tari-project/tari/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/tari-project/tari/merges",
            "archive_url": "https://api.github.com/repos/tari-project/tari/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/tari-project/tari/downloads",
            "issues_url": "https://api.github.com/repos/tari-project/tari/issues{/number}",
            "pulls_url": "https://api.github.com/repos/tari-project/tari/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/tari-project/tari/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/tari-project/tari/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/tari-project/tari/labels{/name}",
            "releases_url": "https://api.github.com/repos/tari-project/tari/releases{/id}",
            "deployments_url": "https://api.github.com/repos/tari-project/tari/deployments",
            "created_at": "2018-06-07T10:09:08Z",
            "updated_at": "2022-08-03T01:21:52Z",
            "pushed_at": "2022-08-05T14:00:50Z",
            "git_url": "git://github.com/tari-project/tari.git",
            "ssh_url": "git@github.com:tari-project/tari.git",
            "clone_url": "https://github.com/tari-project/tari.git",
            "svn_url": "https://github.com/tari-project/tari",
            "homepage": "https://tari.com",
            "size": 115832,
            "stargazers_count": 275,
            "watchers_count": 275,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": true,
            "forks_count": 530,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 109,
            "license": {
                "key": "bsd-3-clause",
                "name": "BSD 3-Clause \"New\" or \"Revised\" License",
                "spdx_id": "BSD-3-Clause",
                "url": "https://api.github.com/licenses/bsd-3-clause",
                "node_id": "MDc6TGljZW5zZTU="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "hacktoberfest",
                "rust",
                "tari"
            ],
            "visibility": "public",
            "forks": 530,
            "open_issues": 109,
            "watchers": 275,
            "default_branch": "development"
        }
    },
    "base": {
        "label": "tari-project:development",
        "ref": "development",
        "sha": "e2ac38bcc464d87147ac813a8b99c439c5cf35cb",
        "user": {
            "login": "tari-project",
            "id": 37560539,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
            "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tari-project",
            "html_url": "https://github.com/tari-project",
            "followers_url": "https://api.github.com/users/tari-project/followers",
            "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
            "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
            "organizations_url": "https://api.github.com/users/tari-project/orgs",
            "repos_url": "https://api.github.com/users/tari-project/repos",
            "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tari-project/received_events",
            "type": "Organization",
            "site_admin": false
        },
        "repo": {
            "id": 136459099,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMzY0NTkwOTk=",
            "name": "tari",
            "full_name": "tari-project/tari",
            "private": false,
            "owner": {
                "login": "tari-project",
                "id": 37560539,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
                "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/tari-project",
                "html_url": "https://github.com/tari-project",
                "followers_url": "https://api.github.com/users/tari-project/followers",
                "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
                "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
                "organizations_url": "https://api.github.com/users/tari-project/orgs",
                "repos_url": "https://api.github.com/users/tari-project/repos",
                "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
                "received_events_url": "https://api.github.com/users/tari-project/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/tari-project/tari",
            "description": "The Tari protocol",
            "fork": false,
            "url": "https://api.github.com/repos/tari-project/tari",
            "forks_url": "https://api.github.com/repos/tari-project/tari/forks",
            "keys_url": "https://api.github.com/repos/tari-project/tari/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/tari-project/tari/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/tari-project/tari/teams",
            "hooks_url": "https://api.github.com/repos/tari-project/tari/hooks",
            "issue_events_url": "https://api.github.com/repos/tari-project/tari/issues/events{/number}",
            "events_url": "https://api.github.com/repos/tari-project/tari/events",
            "assignees_url": "https://api.github.com/repos/tari-project/tari/assignees{/user}",
            "branches_url": "https://api.github.com/repos/tari-project/tari/branches{/branch}",
            "tags_url": "https://api.github.com/repos/tari-project/tari/tags",
            "blobs_url": "https://api.github.com/repos/tari-project/tari/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/tari-project/tari/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/tari-project/tari/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/tari-project/tari/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/tari-project/tari/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/tari-project/tari/languages",
            "stargazers_url": "https://api.github.com/repos/tari-project/tari/stargazers",
            "contributors_url": "https://api.github.com/repos/tari-project/tari/contributors",
            "subscribers_url": "https://api.github.com/repos/tari-project/tari/subscribers",
            "subscription_url": "https://api.github.com/repos/tari-project/tari/subscription",
            "commits_url": "https://api.github.com/repos/tari-project/tari/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/tari-project/tari/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/tari-project/tari/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/tari-project/tari/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/tari-project/tari/contents/{+path}",
            "compare_url": "https://api.github.com/repos/tari-project/tari/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/tari-project/tari/merges",
            "archive_url": "https://api.github.com/repos/tari-project/tari/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/tari-project/tari/downloads",
            "issues_url": "https://api.github.com/repos/tari-project/tari/issues{/number}",
            "pulls_url": "https://api.github.com/repos/tari-project/tari/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/tari-project/tari/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/tari-project/tari/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/tari-project/tari/labels{/name}",
            "releases_url": "https://api.github.com/repos/tari-project/tari/releases{/id}",
            "deployments_url": "https://api.github.com/repos/tari-project/tari/deployments",
            "created_at": "2018-06-07T10:09:08Z",
            "updated_at": "2022-08-03T01:21:52Z",
            "pushed_at": "2022-08-05T14:00:50Z",
            "git_url": "git://github.com/tari-project/tari.git",
            "ssh_url": "git@github.com:tari-project/tari.git",
            "clone_url": "https://github.com/tari-project/tari.git",
            "svn_url": "https://github.com/tari-project/tari",
            "homepage": "https://tari.com",
            "size": 115832,
            "stargazers_count": 275,
            "watchers_count": 275,
            "language": "Rust",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": true,
            "forks_count": 530,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 109,
            "license": {
                "key": "bsd-3-clause",
                "name": "BSD 3-Clause \"New\" or \"Revised\" License",
                "spdx_id": "BSD-3-Clause",
                "url": "https://api.github.com/licenses/bsd-3-clause",
                "node_id": "MDc6TGljZW5zZTU="
            },
            "allow_forking": true,
            "is_template": false,
            "web_commit_signoff_required": false,
            "topics": [
                "hacktoberfest",
                "rust",
                "tari"
            ],
            "visibility": "public",
            "forks": 530,
            "open_issues": 109,
            "watchers": 275,
            "default_branch": "development"
        }
    },
    "_links": {
        "self": {
            "href": "https://api.github.com/repos/tari-project/tari/pulls/1000"
        },
        "html": {
            "href": "https://github.com/tari-project/tari/pull/1000"
        },
        "issue": {
            "href": "https://api.github.com/repos/tari-project/tari/issues/1000"
        },
        "comments": {
            "href": "https://api.github.com/repos/tari-project/tari/issues/1000/comments"
        },
        "review_comments": {
            "href": "https://api.github.com/repos/tari-project/tari/pulls/1000/comments"
        },
        "review_comment": {
            "href": "https://api.github.com/repos/tari-project/tari/pulls/comments{/number}"
        },
        "commits": {
            "href": "https://api.github.com/repos/tari-project/tari/pulls/1000/commits"
        },
        "statuses": {
            "href": "https://api.github.com/repos/tari-project/tari/statuses/f862e3d6ed6c9158ad51d77c14af839b1e45489f"
        }
    },
    "author_association": "COLLABORATOR",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": true,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "unknown",
    "merged_by": {
        "login": "CjS77",
        "id": 7573551,
        "node_id": "MDQ6VXNlcjc1NzM1NTE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7573551?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CjS77",
        "html_url": "https://github.com/CjS77",
        "followers_url": "https://api.github.com/users/CjS77/followers",
        "following_url": "https://api.github.com/users/CjS77/following{/other_user}",
        "gists_url": "https://api.github.com/users/CjS77/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CjS77/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CjS77/subscriptions",
        "organizations_url": "https://api.github.com/users/CjS77/orgs",
        "repos_url": "https://api.github.com/users/CjS77/repos",
        "events_url": "https://api.github.com/users/CjS77/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CjS77/received_events",
        "type": "User",
        "site_admin": false
    },
    "comments": 2,
    "review_comments": 3,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 2,
    "deletions": 1,
    "changed_files": 1
}
    "#;
}

pub mod repositories {
    pub const TARI_REPO: &str = r#"
{
    "id": 136459099,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMzY0NTkwOTk=",
    "name": "tari",
    "full_name": "tari-project/tari",
    "private": false,
    "owner": {
        "login": "tari-project",
        "id": 37560539,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
        "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tari-project",
        "html_url": "https://github.com/tari-project",
        "followers_url": "https://api.github.com/users/tari-project/followers",
        "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
        "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
        "organizations_url": "https://api.github.com/users/tari-project/orgs",
        "repos_url": "https://api.github.com/users/tari-project/repos",
        "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tari-project/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "html_url": "https://github.com/tari-project/tari",
    "description": "The Tari protocol",
    "fork": false,
    "url": "https://api.github.com/repos/tari-project/tari",
    "forks_url": "https://api.github.com/repos/tari-project/tari/forks",
    "keys_url": "https://api.github.com/repos/tari-project/tari/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/tari-project/tari/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/tari-project/tari/teams",
    "hooks_url": "https://api.github.com/repos/tari-project/tari/hooks",
    "issue_events_url": "https://api.github.com/repos/tari-project/tari/issues/events{/number}",
    "events_url": "https://api.github.com/repos/tari-project/tari/events",
    "assignees_url": "https://api.github.com/repos/tari-project/tari/assignees{/user}",
    "branches_url": "https://api.github.com/repos/tari-project/tari/branches{/branch}",
    "tags_url": "https://api.github.com/repos/tari-project/tari/tags",
    "blobs_url": "https://api.github.com/repos/tari-project/tari/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/tari-project/tari/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/tari-project/tari/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/tari-project/tari/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/tari-project/tari/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/tari-project/tari/languages",
    "stargazers_url": "https://api.github.com/repos/tari-project/tari/stargazers",
    "contributors_url": "https://api.github.com/repos/tari-project/tari/contributors",
    "subscribers_url": "https://api.github.com/repos/tari-project/tari/subscribers",
    "subscription_url": "https://api.github.com/repos/tari-project/tari/subscription",
    "commits_url": "https://api.github.com/repos/tari-project/tari/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/tari-project/tari/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/tari-project/tari/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/tari-project/tari/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/tari-project/tari/contents/{+path}",
    "compare_url": "https://api.github.com/repos/tari-project/tari/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/tari-project/tari/merges",
    "archive_url": "https://api.github.com/repos/tari-project/tari/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/tari-project/tari/downloads",
    "issues_url": "https://api.github.com/repos/tari-project/tari/issues{/number}",
    "pulls_url": "https://api.github.com/repos/tari-project/tari/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/tari-project/tari/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/tari-project/tari/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/tari-project/tari/labels{/name}",
    "releases_url": "https://api.github.com/repos/tari-project/tari/releases{/id}",
    "deployments_url": "https://api.github.com/repos/tari-project/tari/deployments",
    "created_at": "2018-06-07T10:09:08Z",
    "updated_at": "2022-08-03T01:21:52Z",
    "pushed_at": "2022-08-05T14:00:50Z",
    "git_url": "git://github.com/tari-project/tari.git",
    "ssh_url": "git@github.com:tari-project/tari.git",
    "clone_url": "https://github.com/tari-project/tari.git",
    "svn_url": "https://github.com/tari-project/tari",
    "homepage": "https://tari.com",
    "size": 115832,
    "stargazers_count": 275,
    "watchers_count": 275,
    "language": "Rust",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "forks_count": 530,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 109,
    "license": {
        "key": "bsd-3-clause",
        "name": "BSD 3-Clause \"New\" or \"Revised\" License",
        "spdx_id": "BSD-3-Clause",
        "url": "https://api.github.com/licenses/bsd-3-clause",
        "node_id": "MDc6TGljZW5zZTU="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "hacktoberfest",
        "rust",
        "tari"
    ],
    "visibility": "public",
    "forks": 530,
    "open_issues": 109,
    "watchers": 275,
    "default_branch": "development",
    "temp_clone_token": null,
    "organization": {
        "login": "tari-project",
        "id": 37560539,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM3NTYwNTM5",
        "avatar_url": "https://avatars.githubusercontent.com/u/37560539?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tari-project",
        "html_url": "https://github.com/tari-project",
        "followers_url": "https://api.github.com/users/tari-project/followers",
        "following_url": "https://api.github.com/users/tari-project/following{/other_user}",
        "gists_url": "https://api.github.com/users/tari-project/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tari-project/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tari-project/subscriptions",
        "organizations_url": "https://api.github.com/users/tari-project/orgs",
        "repos_url": "https://api.github.com/users/tari-project/repos",
        "events_url": "https://api.github.com/users/tari-project/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tari-project/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "network_count": 530,
    "subscribers_count": 29
}
    "#;
}

pub mod users {
    pub const CJS77: &str = r#"
            {
                "login": "CjS77",
                "id": 7573551,
                "node_id": "MDQ6VXNlcjc1NzM1NTE=",
                "avatar_url": "https://avatars.githubusercontent.com/u/7573551?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/CjS77",
                "html_url": "https://github.com/CjS77",
                "followers_url": "https://api.github.com/users/CjS77/followers",
                "following_url": "https://api.github.com/users/CjS77/following{/other_user}",
                "gists_url": "https://api.github.com/users/CjS77/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/CjS77/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/CjS77/subscriptions",
                "organizations_url": "https://api.github.com/users/CjS77/orgs",
                "repos_url": "https://api.github.com/users/CjS77/repos",
                "events_url": "https://api.github.com/users/CjS77/events{/privacy}",
                "received_events_url": "https://api.github.com/users/CjS77/received_events",
                "type": "User",
                "site_admin": false,
                "name": "Cayle Sharrock",
                "company": null,
                "blog": "",
                "location": "Portugal",
                "email": null,
                "hireable": null,
                "bio": null,
                "twitter_username": null,
                "public_repos": 56,
                "public_gists": 10,
                "followers": 65,
                "following": 0,
                "created_at": "2014-05-13T20:06:19Z",
                "updated_at": "2022-08-02T10:53:39Z"
            }"#;

    pub const STRINGHANDLER: &str = r#"
            {
                "login": "stringhandler",
                "id": 4200336,
                "node_id": "MDQ6VXNlcjQyMDAzMzY=",
                "avatar_url": "https://avatars.githubusercontent.com/u/4200336?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/stringhandler",
                "html_url": "https://github.com/stringhandler",
                "followers_url": "https://api.github.com/users/stringhandler/followers",
                "following_url": "https://api.github.com/users/stringhandler/following{/other_user}",
                "gists_url": "https://api.github.com/users/stringhandler/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/stringhandler/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stringhandler/subscriptions",
                "organizations_url": "https://api.github.com/users/stringhandler/orgs",
                "repos_url": "https://api.github.com/users/stringhandler/repos",
                "events_url": "https://api.github.com/users/stringhandler/events{/privacy}",
                "received_events_url": "https://api.github.com/users/stringhandler/received_events",
                "type": "User",
                "site_admin": false,
                "name": "stringhandler",
                "blog": "",
                "location": null,
                "email": null,
                "hireable": null,
                "bio": null,
                "twitter_username": null,
                "public_repos": 39,
                "public_gists": 2,
                "followers": 14,
                "following": 6,
                "created_at": "2013-04-19T10:15:35Z",
                "updated_at": "2022-05-28T16:52:48Z"
            }
            "#;
}

pub mod issues {
    pub const ISSUE: &str = r#"
{
    "url": "https://api.github.com/repos/tari-project/tari-crypto/issues/72",
    "repository_url": "https://api.github.com/repos/tari-project/tari-crypto",
    "labels_url": "https://api.github.com/repos/tari-project/tari-crypto/issues/72/labels{/name}",
    "comments_url": "https://api.github.com/repos/tari-project/tari-crypto/issues/72/comments",
    "events_url": "https://api.github.com/repos/tari-project/tari-crypto/issues/72/events",
    "html_url": "https://github.com/tari-project/tari-crypto/issues/72",
    "id": 1094340690,
    "node_id": "I_kwDODjKno85BOlBS",
    "number": 72,
    "title": "Add elliptic curve marker trait?",
    "user": {
        "login": "CjS77",
        "id": 7573551,
        "node_id": "MDQ6VXNlcjc1NzM1NTE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7573551?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CjS77",
        "html_url": "https://github.com/CjS77",
        "followers_url": "https://api.github.com/users/CjS77/followers",
        "following_url": "https://api.github.com/users/CjS77/following{/other_user}",
        "gists_url": "https://api.github.com/users/CjS77/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CjS77/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CjS77/subscriptions",
        "organizations_url": "https://api.github.com/users/CjS77/orgs",
        "repos_url": "https://api.github.com/users/CjS77/repos",
        "events_url": "https://api.github.com/users/CjS77/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CjS77/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 1826486794,
            "node_id": "MDU6TGFiZWwxODI2NDg2Nzk0",
            "url": "https://api.github.com/repos/tari-project/tari-crypto/labels/good%20first%20issue",
            "name": "good first issue",
            "color": "7057ff",
            "default": true,
            "description": "Good for newcomers"
        },
        {
            "id": 3700746084,
            "node_id": "LA_kwDODjKno87clOdk",
            "url": "https://api.github.com/repos/tari-project/tari-crypto/labels/chores",
            "name": "chores",
            "color": "C0AB49",
            "default": false,
            "description": "Tidying up; removing tech debt"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-01-05T13:16:45Z",
    "updated_at": "2022-01-05T13:23:32Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "Consider\r\n```rust\r\nimpl<P, K> SchnorrSignature<P, K>\r\nwhere\r\n    P: PublicKey<K = K>,\r\n    K: SecretKey,\r\n{...}\r\n```\r\n\r\nThis is a nice, clean interface imo, but we implicitly assume that the `P` and `K` live on an elliptic curve. If we introduce an RSA public-private keypair implementation to this create in the future for example, then we could still impl the `PublicKey` and `PrivaeKey` traits, but Schnorr signature should not be allowed.\r\n\r\nA simple solution is to create marker trait: \r\n`pub trait EllipticCurve {}` and implement it for say Ristretto, but not our hypothetical RSA keypair",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/tari-project/tari-crypto/issues/72/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/tari-project/tari-crypto/issues/72/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}
    "#;
}
