on: [push, pull_request]

name: Run test suite

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly-2022-09-13
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: test/debug
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: test/release
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
